In [3]:
import numpy as np

# Load the NPY file
data = np.load('a006_2_gsn.npy')

# View the loaded data
print(data.shape)
print(data)

(167570, 4)
[[-0.69660214  1.22432237 -0.69660073  1.22432393]
 [-0.69660229  1.22432222 -0.69658948  1.22437271]
 [-0.69660243  1.22432206 -0.69657525  1.22442856]
 ...
 [-3.17213946  4.98853892  0.99359451  0.7390105 ]
 [-3.17213946  4.98853892  0.99359451  0.7390105 ]
 [-3.17213946  4.98853892  0.99359458  0.73901055]]
